services:

  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: env/dev/Dockerfile
      args:
        BUILD_ENV: dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BUILD_TIME=FDFFDDF
    ports:
      - "7841:7841"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - intranet

volumes:
  node_modules:

networks:
  intranet: